name: uci_client
description: UCI app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  auto_route: ^0.5.0
  flutter_secure_storage: ^3.3.3
  url_launcher: ^5.4.10
  flutter_image_compress: ^0.6.8
  image_picker: ^0.6.7
  circular_profile_avatar: ^1.0.6
  eosdart:
    git: https://github.com/tapkain/eosdart.git

  provider: ^4.1.2
  flutter_form_builder: ^3.10.1
  introduction_screen: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  auto_route_generator: ^0.5.0
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/uci.png'

flutter:
  uses-material-design: true
  fonts:
    - family: FavoritStd
      fonts:
        - asset: assets/fonts/FavoritStd/FavoritStd-LightExtended.otf
          weight: 100
        - asset: assets/fonts/FavoritStd/FavoritStd-LightExtended.otf
          weight: 200
        - asset: assets/fonts/FavoritStd/FavoritStd-LightExtended.otf
          weight: 300
        - asset: assets/fonts/FavoritStd/FavoritStd-RegularExtended.otf
          weight: 400
        - asset: assets/fonts/FavoritStd/FavoritStd-MediumExtended.otf
          weight: 500
        - asset: assets/fonts/FavoritStd/FavoritStd-MediumExtended.otf
          weight: 600
        - asset: assets/fonts/FavoritStd/FavoritStd-BoldExtended.otf
          weight: 700
        - asset: assets/fonts/FavoritStd/FavoritStd-BoldExtended.otf
          weight: 800
        - asset: assets/fonts/FavoritStd/FavoritStd-BoldExtended.otf
          weight: 900

    - family: Favorit
      fonts:
        - asset: assets/fonts/Favorit/FavoritTrial-Light.otf
          weight: 100
        - asset: assets/fonts/Favorit/FavoritTrial-Light.otf
          weight: 200
        - asset: assets/fonts/Favorit/FavoritTrial-Light.otf
          weight: 300
        - asset: assets/fonts/Favorit/FavoritTrial-Regular.otf
          weight: 400
        - asset: assets/fonts/Favorit/FavoritTrial-Medium.otf
          weight: 500
        - asset: assets/fonts/Favorit/FavoritTrial-Medium.otf
          weight: 600
        - asset: assets/fonts/Favorit/FavoritTrial-Bold.otf
          weight: 700
        - asset: assets/fonts/Favorit/FavoritTrial-Bold.otf
          weight: 800
        - asset: assets/fonts/Favorit/FavoritTrial-Bold.otf
          weight: 900

  assets:
    - assets/uci.png
    - assets/