name: uci_client
description: UCI app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  auto_route: ^0.5.0
  flutter_secure_storage: ^3.3.3
  eosdart: ^0.4.4
  provider: ^4.1.2

dev_dependencies:
  auto_route_generator: ^0.5.0
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

flutter:
  uses-material-design: true